config/routes.rb
Rails.application.routes.draw do
  resources :patients
  devise_for :users
  root 'publics#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'doctor', to: 'publics#doctor', as: :doctor
  get 'receptionist', to: 'publics#receptionist', as: :receptionist
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can %i[read create], Patient
    can %i[destroy update], Patient, user: user
    return unless user.doctor?

    can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  paginates_per 20
  enum sex: %i[female male].freeze
  validates :first_name, :last_name, :birthdate, :sex, :address_line1, :address_line2, :city,
            :state, :country, :phone, :email, :user_id, presence: true
  validates :first_name, :last_name, length: { in: 2..20 }
  validates :address_line1, :address_line2, length: { in: 6..70 }
  validates :email,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: 'Invalid format' }

  validates :phone,
            format: { with: /([0-9\s\-]{7,})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?\z/, message: 'Invalid format' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  enum role: %i[receptionist doctor].freeze
  validates :email, :password, :role, presence: true
  validates :password, length: { in: 10..40 }

  has_many :patients
  validates_associated :patients

  after_initialize :set_default_role, if: :new_record?

  private

  def set_default_role
    self.role ||= :receptionist
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  check_authorization unless: :devise_controller?
  before_action :authenticate_user!

  def after_sign_in_path_for(_resource)
    if current_user.role == 'doctor'
      doctor_path
    else
      receptionist_path
    end
  end
  rescue_from CanCan::AccessDenied do |exception|
    if current_user.nil?
      session[:next] = request.fullpath
      redirect_to login_url, alert: 'You have to log in to continue.'
    else
      respond_to do |format|
        format.json { render nothing: true, status: :not_found }
        format.html { redirect_to main_app.root_url, alert: exception.message }
        format.js { render nothing: true, status: :not_found }
      end
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  load_and_authorize_resource

  # GET /patients or /patients.json
  def index
    @patients = Patient.order(created_at: :desc).page(params[:page])
  end

  # GET /patients/1 or /patients/1.json
  def show; end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit; end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)
    @patient.user_id = current_user.id

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity, notice: @patient.errors }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :birthdate, :sex, :address_line1, :address_line2, :city,
                                    :state, :country, :phone, :email, :user_id)
  end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  skip_authorization_check
  def index; end

  def doctor
    @page = 'doctor'
    sort_column = params[:sort] || 'created_at'
    sort_direction = params[:direction].presence_in(%w[asc desc]) || 'desc'
    @patients = Patient.order("#{sort_column} #{sort_direction}").page(params[:page]).per(10)
  end

  def receptionist
    @page = 'receptionist'

    sort_column = params[:sort] || 'created_at'
    sort_direction = params[:direction].presence_in(%w[asc desc]) || 'desc'

    @patients = Patient.order("#{sort_column} #{sort_direction}").page(params[:page]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable_table_header(title, column, path_method, **)
    content_tag(:th, class: 'patients_th', scope: 'col') do
      sortable_column(title, column, path_method)
    end
  end

  def sortable_column(title, column, path_method, **)
    direction = column.to_s == params[:sort].to_s && params[:direction] == 'asc' ? 'desc' : 'asc'

    query_params = request.query_parameters.merge(sort: column, direction: direction)

    path = send(path_method, query_params)
    link_to(path, data: { turbo_action: 'advance' }, class: 'h-content d-flex align-items-center', **) do
      concat title
      concat sort_icon(column)
    end
  end

  def sort_icon(column)
    return unless params[:sort].to_s == column.to_s

    if params[:direction] == 'asc'
      svg_icon('M5 15l7-7 7 7')
    else
      svg_icon('M19 9l-7 7-7-7')
    end
  end

  def svg_icon(path_d)
    content_tag(:svg, xmlns: 'http://www.w3.org/2000/svg', class: 'ml-1 inline w-4 h-4', fill: 'none',
                      viewBox: '0 0 24 24', stroke: 'currentColor') do
      "<path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='#{path_d}'></path>".html_safe
    end
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hello Doctor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body>
    <% if current_user %>
      <%= render 'shared/header' %>
    <% end %>
    <main class="container">
      <%= render 'shared/notification' %>
      <%= yield %>
    </main>
    <% if current_user %>
      <%= render 'shared/footer' %>
    <% end %>
  </body>
</html>

app/views/patients/_form.html.erb
<div class="col col-md-6">
  <%= form_with(model: patient) do |form| %>
    <% if patient.errors.any? %>
      <div class="text-danger">
        <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>
        <ul>
          <% patient.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="mb-3">
      <%= form.label :first_name, class: "form-label" %>
      <%= form.text_field :first_name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :last_name, class: "form-label" %>
      <%= form.text_field :last_name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :birthdate, class: "form-label" %>
      <%= form.date_field :birthdate, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :sex, class: "form-label" %>
      <%= form.select :sex, Patient.sexes.keys, { prompt: 'Add patient sex' }, class: "form-select" %>
    </div>
    <div class="mb-3">
      <%= form.label :address_line1, class: "form-label" %>
      <%= form.text_field :address_line1, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :address_line2, class: "form-label" %>
      <%= form.text_field :address_line2 , class: "form-control"%>
    </div>
    <div class="mb-3">
      <%= form.label :city, class: "form-label" %>
      <%= form.text_field :city, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :state, class: "form-label" %>
      <%= form.text_field :state , class: "form-control"%>
    </div>
    <div class="mb-3">
      <%= form.label :country, class: "form-label" %>
      <%= form.text_field :country, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :phone, class: "form-label" %>
      <%= form.number_field :phone, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :email, class: "form-label" %>
      <%= form.text_field :email, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.submit class: "btn btn-success"%>
    </div>
  <% end %>
</div>

app/views/patients/_patient.html.erb
<div class="card" style="width: 18rem;" id="<%= dom_id patient %>">
  <div class="card-body">
    <h5 class="card-title"> <%= patient.first_name %>&nbsp;<%= patient.last_name %></h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">Patient data</h6>
    <p class="card-text">
      <strong>First name:</strong>
      <%= patient.first_name %>
    </p>
    <p class="card-text">
      <strong>Last name:</strong>
      <%= patient.last_name %>
    </p>
    <p class="card-text">
      <strong>Phone:</strong>
      <%= patient.phone %>
    </p>
    <p class="card-text">
      <strong>Email:</strong>
      <%= patient.email %>
    </p>
    <p class="card-text">
      <strong>Birthdate:</strong>
      <%= patient.birthdate %>
    </p>
    <p class="card-text">
      <strong>Patient since:</strong>
      <%= patient.created_at.strftime("%B %e, %Y")  %>
    </p>
    <p class="card-text">
      <strong>Sex:</strong>
      <%= patient.sex %>
    </p>
    <p class="card-text">
      <strong>Address line1:</strong>
      <%= patient.address_line1 %>
    </p>
    <p class="card-text">
      <strong>Address line2:</strong>
      <%= patient.address_line2 %>
    </p>
    <p class="card-text">
      <strong>City:</strong>
      <%= patient.city %>
    </p>
    <p class="card-text">
      <strong>State:</strong>
      <%= patient.state %>
    </p>
    <p class="card-text">
      <strong>Country:</strong>
      <%= patient.country %>
    </p>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', 'javascript:history.back()', class: "btn btn-success" %>
  </div>
</div>

app/views/patients/edit.html.erb
<h1 class="lead">Edit patient data</h1>
<%= render "form", patient: @patient %>
<br>
<hr>
<div class="mt-3">
  <%= link_to "Show this patient", @patient, class: "btn btn-warning" %> |
  <%= link_to 'Back', 'javascript:history.back()', class: "btn btn-primary" %>
</div>

app/views/patients/index.html.erb
<h1 class="lead">Patients</h1>
<div class="mb-3">
  <%= link_to "Add new patient", new_patient_path , class: "btn btn-primary" %>
</div>
<%= line_chart Patient.group_by_day(:created_at).count %>
<%= cache @patients do%>
  <%= paginate @patients %>
  <table  class="table">
    <thead>
      <tr>
        <th scope="col">
          First name
        </th>
        <th scope="col">
          Last name
        </th>
        <th scope="col">
          Email
        </th>
        <th scope="col">
          Phone
        </th>
        <th scope="col">
          Date
        </th>
        <th scope="col">
          Details
        </th>
      </tr>
    </thead>
    <tbody>
      <% @patients.each do |patient| %>
        <%= cache patient do%>
          <tr>
            <td>
              <%= patient.first_name%>
            </td>
            <td>
              <%= patient.last_name%>
            </td>
            <td>
              <%= patient.email%>
            </td>
            <td>
              <%= patient.phone%>
            </td>
            <td>
              <%= patient.created_at %>
            </td>
            <td>
              <%= link_to 'Details', patient_url(patient) %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/patients/new.html.erb
<div class="container">
  <h1 class="lead">Create new patient</h1>
  <%= render "form", patient: @patient %>
  <br>
  <hr>
  <div class="mt-3">
    <%= link_to 'Back', 'javascript:history.back()', class: "btn btn-primary" %>
  </div>
</div>

app/views/patients/show.html.erb
<%= render @patient %>
<div class="mb-3 mt-3 d-md-flex">
  <%= link_to "Edit this patient", edit_patient_path(@patient), class: "btn btn-warning" %> |
  <%= button_to "Destroy this patient", @patient, method: :delete, class: "btn btn-danger"%>
</div>

app/views/publics/doctor.html.erb
<div class="container">
  <h1 class="lead text-primary">This is the doctor page</h1>
  <%= column_chart Patient.group_by_month(:created_at).count %>
  <%= pie_chart Patient.group(:sex).count %>
  <%= turbo_frame_tag "patients" do %>
    <%= cache @patients do%>
      <%= paginate @patients %>
      <table  class="table">
        <thead>
          <tr>
            <%= sortable_table_header 'First name', :first_name, :doctor_path, class: 'invoices__row--header' %>
            <%= sortable_table_header 'Last name', :last_name, :doctor_path, class: 'invoices__row--header' %>
            <%= sortable_table_header 'Sex', :sex, :doctor_path, class: 'invoices__row--header' %>
            <%= sortable_table_header 'Created At', :created_at, :doctor_path, class: 'invoices__row--header' %>
            <%= sortable_table_header 'Phone', :phone, :doctor_path, class: 'invoices__row--header' %>
            <%= sortable_table_header 'Email', :email, :doctor_path, class: 'invoices__row--header' %>
            <th scope="col">
              Details
            </th>
          </tr>
        </thead>
        <tbody>
          <% @patients.each do |patient| %>
            <%= cache patient do%>
              <tr>
                <td>
                  <%= patient.first_name %>
                </td>
                <td>
                  <%= patient.last_name %>
                </td>
                <td>
                  <%= patient.sex %>
                </td>
                <td>
                  <%= patient.created_at %>
                </td>
                <td>
                  <%= patient.phone %>
                </td>
                <td>
                  <%= patient.email %>
                </td>
                <td>
                  <%= link_to 'Details', patient_url(patient) %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <% end %>
  <% end %>
</div>

app/views/publics/index.html.erb
<div class="container">
  <h1 class="lead">Hello Doctor</h1>
  <p class="text-primary">Patients records managing system</p>
</div>

app/views/publics/receptionist.html.erb
<div class="container">
  <h1>Receptionist</h1>
  <%= turbo_frame_tag "patients" do %>
    <%= cache @patients do%>
      <%= paginate @patients %>
      <table  class="table">
        <thead>
          <tr>
            <%= sortable_table_header 'First name', :first_name, :receptionist_path, class: 'invoices__row--header' %>
            <%= sortable_table_header 'Last name', :last_name, :receptionist_path, class: 'invoices__row--header' %>
            <%= sortable_table_header 'Sex', :sex, :receptionist_path, class: 'invoices__row--header' %>
            <%= sortable_table_header 'Created At', :created_at, :receptionist_path, class: 'invoices__row--header' %>
            <%= sortable_table_header 'Phone', :phone, :receptionist_path, class: 'invoices__row--header' %>
            <%= sortable_table_header 'Email', :email, :receptionist_path, class: 'invoices__row--header' %>
            <th scope="col">
              Details
            </th>
          </tr>
        </thead>
        <tbody>
          <% @patients.each do |patient| %>
            <%= cache patient do%>
              <tr>
                <td>
                  <%= patient.first_name %>
                </td>
                <td>
                  <%= patient.last_name %>
                </td>
                <td>
                  <%= patient.sex %>
                </td>
                <td>
                  <%= patient.created_at %>
                </td>
                <td>
                  <%= patient.phone %>
                </td>
                <td>
                  <%= patient.email %>
                </td>
                <td>
                  <%= link_to 'Details', patient_url(patient) %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <% end %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: "nav-link px-2 text-body-secondary" %>
      </li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
    <p class="text-center text-body-secondary">&copy; 2024 Hello Doctor, Inc</p>
  </footer>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation" data-controller="navigation">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Hello Doctor</a>
    <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault" >
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <% if current_user.role == 'doctor' %>
            <%= link_to 'Dashboard', doctor_path  , class: "nav-link active", aria: {current: "page"} %>
          <% else %>
            <%= link_to 'Dashboard', receptionist_path  , class: "nav-link active", aria: {current: "page"} %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to 'Patients', patients_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <% if user_signed_in? %>
        <div class="mx-2">
          <%= link_to 'Logout', destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "are you sure" } , class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_notification.html.erb
<% if notice %>
  <p class="text-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="text-danger"><%= alert %></p>
<% end %>